---

- hosts: "{{ OPT_HOSTS | default('undefined') }}"
  become: yes
  become_method: sudo

  tasks:
    - name: Connection test
      shell: uname -a
      register: out_uname

    - debug: var=out_uname.stdout_lines
       