---

- hosts: "{{ OPT_HOSTS | default('undefined') }}"
  become: yes
  become_method: sudo

  roles:
    - create-hardlink


- hosts: master
  become: yes
  become_method: sudo

  roles:
    - create-drop-table-sql
